#!/bin/bash

apt-get update
apt-get -y install postgresql postgresql-contrib

wget https://raw.githubusercontent.com/NoRyyZ/Auktionshaus/master/Auktionshaus_SQL

su postgres -c "echo ${DB_PASSWORD} | createuser ${DB_USER} --password"
su postgres -c "createdb -O ${DB_USER} ${DB_NAME}"
sudo -u postgres psql -d ${DB_NAME} < Auktionshaus_SQL


echo "listen_addresses='*'" >> /etc/postgresql/*/main/postgresql.conf
echo "host all all 192.168.42.0/24 trust" >> /etc/postgresql/*/main/pg_hba.conf
service postgresql restart
