#!/bin/bash

sudo apt-get update
sudo apt-get install -y nodejs

if [ -d "Auktionshaus" ]; 
then
  cd Auktionshaus
  git fetch https://github.com/NoRyyZ/Auktionshaus
else
  git clone https://github.com/NoRyyZ/Auktionshaus
  cd Auktionshaus
fi
nodejs app.js --port ${WEB_PORT} --db ${DB_ADDRESS} --db_port ${DB_PORT} --db_user ${DB_USER} --db_pw ${DB_PASSWORD} --db_name ${DB_NAME}&
